openapi: "3.0.0"

info:
  description: This is a server for voice-based gender recognition.
  title: Gender recognition
  version: "1.0"
servers:
  - url: http://localhost:9090/v1.0

tags:
  - name: Gender recognition
    description: Gender recognition based on uploaded audio signal

paths:
  /recognition:
    post:
      tags:
        - Gender recognition
      summary: Recognizes gender
      description: Gender recognition
      operationId: app.recognize
      requestBody:
        required: True
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audioFile:
                  description: "upload an audio file no longer than 4 seconds in wav format"
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  class:
                    type: string
                  probability:
                    type: number
                    format: float
